#include "data_types.hpp"
#include "jacobian_terms.cuh"

namespace {

// Fills all Jacobian contributions generated by a single Ybus edge. UseAtomic
// selects whether shared diagonal slots are accumulated with atomicAdd.
template <bool UseAtomic>
__device__ __forceinline__ void fill_jacobian_edge_value(
    const YbusCoo ybus,
    int32_t k,
    const float* __restrict__ v_re,
    const float* __restrict__ v_im,
    const float* __restrict__ v_norm_re,
    const float* __restrict__ v_norm_im,
    const int32_t* __restrict__ offdiagJ11,
    const int32_t* __restrict__ offdiagJ21,
    const int32_t* __restrict__ offdiagJ12,
    const int32_t* __restrict__ offdiagJ22,
    const int32_t* __restrict__ diagJ11,
    const int32_t* __restrict__ diagJ21,
    const int32_t* __restrict__ diagJ12,
    const int32_t* __restrict__ diagJ22,
    float* __restrict__ J_values)
{
    // Edge-parallel traversal starts from a flat nonzero id and reads both bus ids.
    const int32_t i = ybus.row[k];
    const int32_t j = ybus.col[k];
    const bool self_edge = (i == j);

    // Convert the complex admittance and current voltage state into reusable
    // local terms for all four Jacobian blocks.
    const float yr = ybus.real[k];
    const float yi = ybus.imag[k];
    const JacobianTerms terms = computeJacobianTerms(
        i, j, yr, yi, v_re, v_im, v_norm_re, v_norm_im
    );

    // Off-diagonal slots are unique per Ybus nonzero in the assembled cases, so
    // they can be written directly. Diagonal slots still accumulate many edges.
    if (!self_edge) {
        // Store off-diagonal block entries for this edge when the reduced
        // Jacobian actually contains the corresponding row/column.
        if (offdiagJ11[k] >= 0) J_values[offdiagJ11[k]] = terms.term_va_re;
        if (offdiagJ21[k] >= 0) J_values[offdiagJ21[k]] = terms.term_va_im;
        if (offdiagJ12[k] >= 0) J_values[offdiagJ12[k]] = terms.term_vm_re;
        if (offdiagJ22[k] >= 0) J_values[offdiagJ22[k]] = terms.term_vm_im;

        // Angle diagonals are the negative sum of neighboring angle terms.
        if constexpr (UseAtomic) {
            if (diagJ11[i] >= 0) atomicAdd(&J_values[diagJ11[i]], -terms.term_va_re);
            if (diagJ21[i] >= 0) atomicAdd(&J_values[diagJ21[i]], -terms.term_va_im);
        } else {
            if (diagJ11[i] >= 0) J_values[diagJ11[i]] += -terms.term_va_re;
            if (diagJ21[i] >= 0) J_values[diagJ21[i]] += -terms.term_va_im;
        }
    }

    // Magnitude diagonals receive one contribution from every incident edge. For
    // the explicit self entry, term_vm and diag_vm collapse into the same slot.
    const float diag_scale = self_edge ? 2.0f : 1.0f;
    if constexpr (UseAtomic) {
        if (diagJ12[i] >= 0) atomicAdd(&J_values[diagJ12[i]], diag_scale * terms.diag_vm_re);
        if (diagJ22[i] >= 0) atomicAdd(&J_values[diagJ22[i]], diag_scale * terms.diag_vm_im);
    } else {
        if (diagJ12[i] >= 0) J_values[diagJ12[i]] += diag_scale * terms.diag_vm_re;
        if (diagJ22[i] >= 0) J_values[diagJ22[i]] += diag_scale * terms.diag_vm_im;
    }
}

}  // namespace

// Production edge-parallel fill: many edges can update one bus diagonal, so
// diagonal accumulation uses atomics.
__global__ void fill_jacobian_edge(YbusCoo ybus,
                                   const float* __restrict__ v_re,
                                   const float* __restrict__ v_im,
                                   const float* __restrict__ v_norm_re,
                                   const float* __restrict__ v_norm_im,
                                   const int32_t* __restrict__ offdiagJ11,
                                   const int32_t* __restrict__ offdiagJ21,
                                   const int32_t* __restrict__ offdiagJ12,
                                   const int32_t* __restrict__ offdiagJ22,
                                   const int32_t* __restrict__ diagJ11,
                                   const int32_t* __restrict__ diagJ21,
                                   const int32_t* __restrict__ diagJ12,
                                   const int32_t* __restrict__ diagJ22,
                                   float* __restrict__ J_values)
{
    // One thread owns one Ybus nonzero.
    const int32_t k = blockIdx.x * blockDim.x + threadIdx.x;
    if (k < ybus.n_edges) {
        fill_jacobian_edge_value<true>(
            ybus, k, v_re, v_im, v_norm_re, v_norm_im,
            offdiagJ11, offdiagJ21, offdiagJ12, offdiagJ22,
            diagJ11, diagJ21, diagJ12, diagJ22, J_values);
    }
}

// Experimental no-atomic variant used when the caller controls conflicts or
// wants to measure the cost of diagonal atomics separately.
__global__ void fill_jacobian_edge_no_atomic(YbusCoo ybus,
                                             const float* __restrict__ v_re,
                                             const float* __restrict__ v_im,
                                             const float* __restrict__ v_norm_re,
                                             const float* __restrict__ v_norm_im,
                                             const int32_t* __restrict__ offdiagJ11,
                                             const int32_t* __restrict__ offdiagJ21,
                                             const int32_t* __restrict__ offdiagJ12,
                                             const int32_t* __restrict__ offdiagJ22,
                                             const int32_t* __restrict__ diagJ11,
                                             const int32_t* __restrict__ diagJ21,
                                             const int32_t* __restrict__ diagJ12,
                                             const int32_t* __restrict__ diagJ22,
                                             float* __restrict__ J_values)
{
    // Same one-thread-per-edge mapping as the atomic kernel.
    const int32_t k = blockIdx.x * blockDim.x + threadIdx.x;
    if (k < ybus.n_edges) {
        fill_jacobian_edge_value<false>(
            ybus, k, v_re, v_im, v_norm_re, v_norm_im,
            offdiagJ11, offdiagJ21, offdiagJ12, offdiagJ22,
            diagJ11, diagJ21, diagJ12, diagJ22, J_values);
    }
}
