#ifndef SPARSE_DIRECT_MATRIX_MARKET_IO_H
#define SPARSE_DIRECT_MATRIX_MARKET_IO_H

#include "matrix/csr_matrix.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    char case_name[128];
    int iteration;
    int matrix_rows;
    int matrix_cols;
    int nnz;
    double rhs_norm_2;
    double cpu_reference_residual;
} DumpMeta;

/*
 * Load a real/integer/complex/pattern Matrix Market coordinate file into
 * zero-based CSR. Duplicate coordinates are summed. Symmetric and Hermitian
 * banners are expanded. For complex files, the real part is stored; ordering
 * code only uses the sparsity pattern.
 */
int load_matrix_market_csr(const char *path, CSRMatrix *A);

/*
 * Load a whitespace-separated vector file.  The returned array is allocated by
 * malloc and must be released by free().
 */
int load_vector_file(const char *path, double **values, int *n);

/*
 * Parse the small meta.json generated by scripts/dump_matpower_systems.py.
 * This is intentionally a tiny key scanner, not a general JSON parser.
 */
int load_dump_meta(const char *path, DumpMeta *meta);

#ifdef __cplusplus
}
#endif

#endif
